package com.demo.entity;

public class TvChannel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tv_channel.t_id
     *
     * @mbg.generated
     */
    private Integer tId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tv_channel.channel_name
     *
     * @mbg.generated
     */
    private String channelName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tv_channel.source_url
     *
     * @mbg.generated
     */
    private String sourceUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tv_channel.parent_id
     *
     * @mbg.generated
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tv_channel.logo_url
     *
     * @mbg.generated
     */
    private String logoUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tv_channel.img_bitmap
     *
     * @mbg.generated
     */
    private String imgBitmap;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tv_channel.t_id
     *
     * @return the value of t_tv_channel.t_id
     *
     * @mbg.generated
     */
    public Integer gettId() {
        return tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tv_channel.t_id
     *
     * @param tId the value for t_tv_channel.t_id
     *
     * @mbg.generated
     */
    public void settId(Integer tId) {
        this.tId = tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tv_channel.channel_name
     *
     * @return the value of t_tv_channel.channel_name
     *
     * @mbg.generated
     */
    public String getChannelName() {
        return channelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tv_channel.channel_name
     *
     * @param channelName the value for t_tv_channel.channel_name
     *
     * @mbg.generated
     */
    public void setChannelName(String channelName) {
        this.channelName = channelName == null ? null : channelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tv_channel.source_url
     *
     * @return the value of t_tv_channel.source_url
     *
     * @mbg.generated
     */
    public String getSourceUrl() {
        return sourceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tv_channel.source_url
     *
     * @param sourceUrl the value for t_tv_channel.source_url
     *
     * @mbg.generated
     */
    public void setSourceUrl(String sourceUrl) {
        this.sourceUrl = sourceUrl == null ? null : sourceUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tv_channel.parent_id
     *
     * @return the value of t_tv_channel.parent_id
     *
     * @mbg.generated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tv_channel.parent_id
     *
     * @param parentId the value for t_tv_channel.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tv_channel.logo_url
     *
     * @return the value of t_tv_channel.logo_url
     *
     * @mbg.generated
     */
    public String getLogoUrl() {
        return logoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tv_channel.logo_url
     *
     * @param logoUrl the value for t_tv_channel.logo_url
     *
     * @mbg.generated
     */
    public void setLogoUrl(String logoUrl) {
        this.logoUrl = logoUrl == null ? null : logoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tv_channel.img_bitmap
     *
     * @return the value of t_tv_channel.img_bitmap
     *
     * @mbg.generated
     */
    public String getImgBitmap() {
        return imgBitmap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tv_channel.img_bitmap
     *
     * @param imgBitmap the value for t_tv_channel.img_bitmap
     *
     * @mbg.generated
     */
    public void setImgBitmap(String imgBitmap) {
        this.imgBitmap = imgBitmap == null ? null : imgBitmap.trim();
    }
}