package com.demo.entity;

import java.util.Date;

import com.alibaba.fastjson.annotation.JSONField;

public class User {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_user.id
	 *
	 * @mbg.generated
	 */
	private Integer id;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_user.username
	 *
	 * @mbg.generated
	 */
	private String username;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_user.password
	 *
	 * @mbg.generated
	 */
	private String password;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_user.email
	 *
	 * @mbg.generated
	 */
	private String email;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_user.disabled
	 *
	 * @mbg.generated
	 */
	private Boolean disabled;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_user.locked
	 *
	 * @mbg.generated
	 */
	private Boolean locked;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_user.locked_time
	 *
	 * @mbg.generated
	 */
	private Date lockedTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_user.create_time
	 *
	 * @mbg.generated
	 */
	@JSONField(format="yyyy-MM-dd HH:mm:ss")
	private Date createTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_user.update_time
	 *
	 * @mbg.generated
	 */
	@JSONField(format="yyyy-MM-dd HH:mm:ss")
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_user.id
	 *
	 * @return the value of t_user.id
	 *
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_user.id
	 *
	 * @param id
	 *            the value for t_user.id
	 *
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_user.username
	 *
	 * @return the value of t_user.username
	 *
	 * @mbg.generated
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_user.username
	 *
	 * @param username
	 *            the value for t_user.username
	 *
	 * @mbg.generated
	 */
	public void setUsername(String username) {
		this.username = username == null ? null : username.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_user.password
	 *
	 * @return the value of t_user.password
	 *
	 * @mbg.generated
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_user.password
	 *
	 * @param password
	 *            the value for t_user.password
	 *
	 * @mbg.generated
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_user.email
	 *
	 * @return the value of t_user.email
	 *
	 * @mbg.generated
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_user.email
	 *
	 * @param email
	 *            the value for t_user.email
	 *
	 * @mbg.generated
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_user.disabled
	 *
	 * @return the value of t_user.disabled
	 *
	 * @mbg.generated
	 */
	public Boolean getDisabled() {
		return disabled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_user.disabled
	 *
	 * @param disabled
	 *            the value for t_user.disabled
	 *
	 * @mbg.generated
	 */
	public void setDisabled(Boolean disabled) {
		this.disabled = disabled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_user.locked
	 *
	 * @return the value of t_user.locked
	 *
	 * @mbg.generated
	 */
	public Boolean getLocked() {
		return locked;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_user.locked
	 *
	 * @param locked
	 *            the value for t_user.locked
	 *
	 * @mbg.generated
	 */
	public void setLocked(Boolean locked) {
		this.locked = locked;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_user.locked_time
	 *
	 * @return the value of t_user.locked_time
	 *
	 * @mbg.generated
	 */
	public Date getLockedTime() {
		return lockedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_user.locked_time
	 *
	 * @param lockedTime
	 *            the value for t_user.locked_time
	 *
	 * @mbg.generated
	 */
	public void setLockedTime(Date lockedTime) {
		this.lockedTime = lockedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_user.create_time
	 *
	 * @return the value of t_user.create_time
	 *
	 * @mbg.generated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_user.create_time
	 *
	 * @param createTime
	 *            the value for t_user.create_time
	 *
	 * @mbg.generated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_user.update_time
	 *
	 * @return the value of t_user.update_time
	 *
	 * @mbg.generated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_user.update_time
	 *
	 * @param updateTime
	 *            the value for t_user.update_time
	 *
	 * @mbg.generated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public User() {

	}

	public User(String username) {
		this.username = username;
	}
}